/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as BattlesIndexImport } from './routes/battles.index'
import { Route as BattlesCreateImport } from './routes/battles.create'
import { Route as BattlesBattleIdImport } from './routes/battles.$battleId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BattlesIndexRoute = BattlesIndexImport.update({
  path: '/battles/',
  getParentRoute: () => rootRoute,
} as any)

const BattlesCreateRoute = BattlesCreateImport.update({
  path: '/battles/create',
  getParentRoute: () => rootRoute,
} as any)

const BattlesBattleIdRoute = BattlesBattleIdImport.update({
  path: '/battles/$battleId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/battles/': {
      id: '/battles/'
      path: '/battles'
      fullPath: '/battles'
      preLoaderRoute: typeof BattlesIndexImport
      parentRoute: typeof rootRoute
    }
    '/battles/create': {
      id: '/battles/create'
      path: '/battles/create'
      fullPath: '/battles/create'
      preLoaderRoute: typeof BattlesCreateImport
      parentRoute: typeof rootRoute
    }
    '/battles/$battleId': {
      id: '/battles/$battleId'
      path: '/battles/$battleId'
      fullPath: '/battles/$battleId'
      preLoaderRoute: typeof BattlesBattleIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  BattlesIndexRoute,
  BattlesCreateRoute,
  BattlesBattleIdRoute,
})

/* prettier-ignore-end */
